eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /infoUsuarios
    health-check-url-path: /healthUsuarios
    metadata-map:
      app-owner: hugo
      description: test application


server:
  port: 3333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
